DROP DATABASE IF EXISTS company;
CREATE DATABASE company;

CREATE TABLE department(
id INTEGER AUTO_INCREMENT PREMARY KEY,
name VARCHAR(30)
);


CREATE TABLE roles(
id INTEGER AUTO_INCREMENT PREMARY KEY,
title VARCHAR(30) NOT NULL,
department_id INTEGER,
FOREIGN KEY(department_id) REFERENCES department(id) ON DELETE SET NULL
);


CREATE TABLE manager(
id INTEGER AUTO_INCREMENT PREMARY KEY,
name VARCHAR(30)
);

CREATE TABLE employee(
id INTEGER AUTO_INCREMENT PREMARY KEY,
first_name VARCHAE(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
manager_id INTEGER,
dept_id INTEGER,
FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE SET NULL
FOREIGN KEY(manager_id) REFERENCES manager(id) ON DELETE SET NULL
FOREIGN KEY(dept_id) REFERENCES department(id) ON DELETE SET NULL
);